---
title: Indivisible SF
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
Subtitle: Resisting the Trump Agenda
email: sahadeva@sahadeva.com
description: "Indivisible SF Pages. Inspired by Indivisible Guide.\n\n"
baseurl: 
url: 
twitter_username: jekyllrb
github_username: jekyll
markdown: kramdown
theme: minima
gems:
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
