---
title: Indivisible SF
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  representatives:
    title: Representatives
    output: false
    phone-numbers:
    -
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    is featured: false
    featured-image:
    call-script:
    Date:
    Location:
    RSVP-link:
    layout: post
subtitle: Resisting the Trump Agenda
email: sahadeva@sahadeva.com
description: "Indivisible SF Pages. Inspired by Indivisible Guide.\n\n"
baseurl:
url:
twitter_username: jekyllrb
github_username: jekyll
background-image: "/uploads/oakland.jpg"
mailchimp-form-id:
markdown: kramdown
theme: minima
gems:
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock

# These defaults determin what fields editors see in CMS

defaults:
- scope:
    type: posts
  values:
    is featured: false
    main-image: # blank values are okay here
    call-script-text:
    Date:
    Location:
    RSVP-link:
    layout: post
- scope:
    type: representatives
  values:
    main-image: # blank values are okay here
    phone-numbers:
    website:
