---
title: Indivisible SF
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  representatives:
    title: Representatives
    output: false
    phone numbers:
    - 
  uploads:
    title: Uploads
    output: true
subtitle: Resisting the Trump Agenda
email: sahadeva@sahadeva.com
description: "Indivisible SF Pages. Inspired by Indivisible Guide.\n\n"
baseurl: 
url: 
twitter_username: jekyllrb
github_username: jekyll
background-image: "/uploads/oakland.jpg"
markdown: kramdown
theme: minima
gems:
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
