---
title: Indivisible SF
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  representatives:
    title: Representatives
    output: false
  uploads:
    title: Uploads
    output: true
  media-items:
    title: media-items
    output: false
defaults:
- scope:
    path: ''
    type: posts
  values:
    is featured: false
    main-image: 
    call-script-text: 
    Date: 
    Location: 
    RSVP-link: 
    layout: post
- scope:
    path: ''
    type: representatives
  values:
    main-image: 
    phone-numbers: 
    website: 
- scope:
    path: ''
    type: media-items
  values:
    main-image: 
subtitle: Resisting the Trump Agenda
email: sahadeva@sahadeva.com
description: Indivisible SF is a group of local residents inspired by the [Indivisible
  Guide](https://www.indivisibleguide.com), which provides a practical framework for
  resisting the Trump agenda. By standing together, we can keep the pressure on our
  representatives to defend progressive values and fight for us in Washington.
baseurl: 
url: 
twitter_username: jekyllrb
github_username: jekyll
facebook_username: jekyll
background-image: "/uploads/oakland.jpg"
mailchimp-form-id: 
markdown: kramdown
theme: minima
gems:
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
